spring.application.name=Student_Management_System
server.port=8082

Spring.datasource.url=jdbc:mysql://root:fHmzzhVIZDyXIvKCPuhqvOlTXEJNdsVz@yamabiko.proxy.rlwy.net:46322/railway
Spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
